#
#
#	Makefile for CS106B codes.
#
#

files: files.cpp genlib.cpp genlib.h
	g++ -std=c++11 genlib.cpp files.cpp -o files -lm

test: test.cpp simpio.cpp simpio.h
	g++ -std=c++11 simpio.cpp test.cpp -o test -lm
