#
#
# Makefile for lec 06 codes.
#
#

class-0: class-0.cpp
	g++ -o class-0 class-0.cpp

class-1: class-1.cpp
	g++ -o class-1 class-1.cpp

class-2: class-2.cpp
	g++ -o class-2 class-2.cpp

class-3: class-3.cpp
	g++ -o class-3 class-3.cpp

class-4: class-4.cpp
	g++ -o class-4 class-4.cpp vector.cpp

class-5: class-5.cpp
	g++ -o class-5 class-5.cpp

cons: constructors.cpp
	g++ -o cons constructors.cpp

cons-1: constructors-1.cpp
	g++ -o cons-1 constructors-1.cpp

access: accessModify.cpp
	g++ -o access accessModify.cpp	
