#
#
# Lecture04's Makefile
#
#

basicA: basicArray.cpp
	g++ -o basicA basicArray.cpp

strexp: stringsExplore.cpp
	g++ -o strexp stringsExplore.cpp

consp: constPoint.cpp
	g++ -o consp constPoint.cpp

point0: pointers-0.cpp
	g++ -o point0 pointers-0.cpp	
