#
#
#	C++ Google
#
#

hello:hello.cpp
	g++ -std=c++14 -o hello hello.cpp

constants:constants.cpp
	g++ -std=c++14 -o constants constants.cpp

loops:loops.cpp
	g++ -std=c++14 -o loops loops.cpp

pointers:pointers.cpp
	g++ -std=c++14 -o pointers pointers.cpp
