#
#	Makefile for :
#	Herbert Schidlt Part II codes
#
#

oops-0: oops-0.cpp googleC++.cpp
	g++ -std=c++14 googleC++.cpp oops-0.cpp -o oops-0 -lm

oops-1: oops-1.cpp googleC++.cpp
	g++ -std=c++14 googleC++.cpp oops-1.cpp -o oops-1 -lm

oops-2: oops-2.cpp googleC++.cpp
	g++ -std=c++14 googleC++.cpp oops-2.cpp -o oops-2 -lm

oops-3: oops-3.cpp googleC++.cpp
	g++ -std=c++14 googleC++.cpp oops-3.cpp -o oops-3 -lm

oops-4: oops-4.cpp googleC++.cpp
	g++ -std=c++14 googleC++.cpp oops-4.cpp -o oops-4 -lm

oops-5: oops-5.cpp googleC++.cpp
	g++ -std=c++14 googleC++.cpp oops-5.cpp -o oops-5 -lm

oops-6: oops-6.cpp googleC++.cpp
	g++ -std=c++14 googleC++.cpp oops-6.cpp -o oops-6 -lm

oops-7: oops-7.cpp googleC++.cpp
	g++ -std=c++14 googleC++.cpp oops-7.cpp -o oops-7 -lm

oops-11: oops-11.cpp googleC++.cpp
	g++ -std=c++14 googleC++.cpp oops-11.cpp -o oops-11 -lm

oops-12.1: oops-12.1.cpp googleC++.cpp
	g++ -std=c++14 googleC++.cpp oops-12.1.cpp -o oops-12.1 -lm
oops-12.2: oops-12.2.cpp googleC++.cpp
	g++ -std=c++14 googleC++.cpp oops-12.2.cpp -o oops-12.2 -lm		
